### PR TITLE
fix(button-modal): fix scrollbar issue and remove scrollable props

### PR DESCRIPTION
**Pull request by piggggggggy**
### To Reviewers
- [ ] Skipping review is not a problem (```style```, ```chore``` ONLY)
- [ ] Not that difficult

### Type of Change
- [ ] New feature
- [x] Bug fixes
- [ ] Feature improvement
- [x] These changes require a usage change
- [ ] Others (performance improvement, refactoring, CI/CD, etc.)

### Checklist
- [x] Updated Storybook documents
- [x] Tested with console

### Description
- button-modal scrollbar issue is fixed
- button-modal scrollable props is removed
- before
image
- after
image

### CODE REVIEW

**Review by yuda110 — APPROVED** [review]
LGTM!

**Review by minseolee — APPROVED** [review]
LGTM ! 👍

**Review by JeoungSulMo — APPROVED** [review]
L G T M!

**Pull request merged**
